### ISSUE TITLE
평소 알바경험 이력도 추가해주세요

### ISSUE THREAD

**Issue by lee0219** [Hwangdonggyu/test-repo#4]
https://github.com/Hwangdonggyu/test-repo/commit/35a0a9514ad40e315a9911575413b62338d2ca34#r104499464
평소 알바경험 이력도 추가해주세요

**Comment by Hwangdonggyu** [comment]
추가했습니다~

**Comment by Hwangdonggyu** [comment]
추가 완료했습니다

**Comment by Hwangdonggyu** [comment]
.
